version: 2

sources:
  - name: tap_atinternet_sp
    description: "
    Données issues de l'API AT Internet Reporting v3, pour le site service-public.fr.
    Seules les données sur les pages avec le titre 'gendarmerie' ont été extraites (principalement
     l'annuaire des brigades, et quelques pages d'informations).
    "
    tables:
      - name: hourly_visits
        description: "
        Visites par jour et heure de la journée
        "
        columns:
          - name: m_bounces
            description: "
            Nombre de visites 'à rebond', c'est à dire avec moins de 2 pages (0 ou 1, peu importe le nombre d’événements).
            "
          - name: m_time_spent_per_visits
            description: "
            Durée moyenne des visites sur le site. Calcul : temps passé cumulé / visites à durée.
            Cette métrique a une portée Visite et est exprimée en millisecondes.
            "
          - name: m_unique_visitors
            description: "
            Nombre de visiteurs (toute personne reconnue la plupart du temps par un cookie et ayant fait au moins 
            1 visite). Ces visiteurs sont bien distincts sur la période.
            "
          - name: m_visits
            description: "
            Une visite se caractérise par un ensemble d'événements qui ont lieu sur votre site (événement 'onsite') 
            par un même visiteur. Si aucun événement n'est mesuré durant une période de temps définie (en général 
            30 minutes), la visite se termine.
            "
          - name: date
            description: "Format: 'YYYY-MM-DD'"
          - name: visit_hour
            description: "
            Heure de la visite (0-23).
            
            ⚠️ Certaines lignes valent 'N/A' dans les données AT Internet, auquel cas la valeur ici sera -1. 
            Cela peut arriver lorsque m_unique_visitors>0 et m_visits=0 par exemple. Donnée à ignorer?
            "
          - name: site_level2

      - name: geo_visits
        description: "
        Visites par lieu (pays, region, ville) et par mois
        "
        columns:
          - name: m_bounces
          - name: m_time_spent_per_visits
          - name: m_unique_visitors
          - name: m_visits
          - name: date_month
            description: "Exemple: 'January', 'February', ..."
          - name: date_year
            description: "Exemple: 2020, 2021"
          - name: date
            description: "
            Mois et années combinés au format 'YYYY-MM-DD' et en utilisant le premier jour du mois (DD=01).
            Exemple: '2020-07-01'
            "
          - name: geo_country
            description: "Exemple: 'France', 'United kingdom'"
          - name: geo_region
            description: "
            En France: correspond à la région, mais à l'étranger: semble correspondre à la ville
            Exemple: 'Pays-de-la-loire', 'London'
            "
          - name: geo_city
            description: "Exemple: 'Saint-brevin-les-pins', 'Belleville', 'Le cergne', 'London'"

      - name: pages_visits
        description: "
        Visites par page et par mois
        "
        columns:
          - name: m_bounces
          - name: m_time_spent_per_visits
          - name: m_unique_visitors
          - name: m_visits
          - name: date_month
          - name: date_year
          - name: date
          - name: site_level2
          - name: page
          - name: page_full_name

      - name: sources_visits
        description: "
        Visites par source et par mois
        "
        columns:
          - name: m_bounces
          - name: m_time_spent_per_visits
          - name: m_unique_visitors
          - name: m_visits
          - name: date_month
          - name: date_year
          - name: date
          - name: src
          - name: src_detail
          - name: src_referrer_url

      - name: devices_visits
        description: "
        Visites par appareil et par mois
        "
        columns:
          - name: m_bounces
          - name: m_time_spent_per_visits
          - name: m_unique_visitors
          - name: m_visits
          - name: date_month
          - name: date_year
          - name: date
          - name: device_type
            description: "Exemple: 'Mobile Phone', 'Desktop', 'Tablet', 'TV'"
          - name: os_group
            description: "Exemple: 'Android', 'iOS', 'Windows', 'macOS', 'Linux'"
          - name: browser_group
            description: "Exemple: 'Safari', 'Chrome Mobile', 'Chrome', 'Firefox'"
          - name: browser_language
            description: "Exemple: 'fr', 'en', 'it'"
